# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
#
# SPDX-License-Identifier: LicenseRef-MIT-BitcoinSuisse
#
<<: !include "./hpack/module.yaml"

name:                tzbtc
# If you update this version, make sure to update it in release.nix
version:             0.8.0

extra-source-files:
- README.md
- CONTRIBUTING.md

category:            Blockchain
description: Wrapped Bitcoin on Tezos Blockchain

library:
  <<: *lib-common

  default-extensions:
    - DerivingStrategies
    - DeriveAnyClass
    - NoApplicativeDo

  dependencies:
    - aeson
    - aeson-casing
    - bytestring
    - co-log
    - containers
    - directory
    - hex-text
    - fmt
    - lorentz
    - morley
    - morley-ledgers
    - morley-multisig
    - morley-prelude
    - morley-upgradeable
    - morley-client
    - named
    - optparse-applicative
    - megaparsec
    - text
    - transformers
    - universum
    - with-utf8
    - safe-exceptions
    - vinyl

executables:
  tzbtc:
    <<: *exec-common

    dependencies:
      - fmt
      - lorentz
      - morley
      - morley-multisig
      - morley-prelude
      - named
      - optparse-applicative
      - safe-exceptions
      - tzbtc

  tzbtc-client:
    main: Main.hs
    source-dirs: client

    dependencies:
      - morley-client
      - morley-prelude
      - named
      - optparse-applicative
      - tzbtc

tests:
  tzbtc-test:
    <<: *test-common

    default-extensions:
      - DerivingStrategies

    dependencies:
    - bytestring
    - co-log
    - co-log-core
    - containers
    - cleveland
    - fmt
    - hex-text
    - HUnit
    - lorentz
    - memory
    - morley
    - morley-client
    - morley-ledgers
    - morley-ledgers-test
    - morley-multisig
    - morley-prelude
    - morley-upgradeable
    - mtl
    - named
    - process
    - tagged
    - tasty
    - tasty-hunit-compat
    - text
    - tzbtc
    - universum
    - with-utf8
