# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
#
# SPDX-License-Identifier: LicenseRef-MIT-BitcoinSuisse
#
# when updating git dependencies, please run
# nix run -f https://github.com/serokell/scratch/archive/master.tar.gz scripts.update-stack-shas -c update-stack-shas
resolver: lts-18.10

packages:
- .

extra-deps:
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    146da727ff486c46b0ec9f392d955f07d797848e # master
  subdirs:
    - code/cleveland
    - code/lorentz
    - code/morley
    - code/morley-client
    - code/morley-prelude

- git:
    https://gitlab.com/morley-framework/morley-multisig.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    b56c2c69eabe9b31075414f393ccad84e766f6fc # master

- git:
    https://gitlab.com/morley-framework/morley-ledgers.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    b39a971f42bb113a5b3e23c9145253e27ad6e049 # master
  subdirs:
    - code/morley-ledgers
    - code/morley-ledgers-test

- git:
    https://gitlab.com/morley-framework/morley-upgradeable.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    0550b5dde3ed1ac2cac6ce53a0e24b077f501a1b # master

- git:
    https://gitlab.com/morley-framework/indigo.git
  commit:
    e879e5f282afb8d25d72d8ba132f22d3d9e628a1 # master
  subdirs:
    - .

- summoner-2.0.1.1@sha256:8ced26ff256e012447e2c6a49a20102511adbea605624f00a059e1e85c366719,6993
- generic-data-0.8.3.0@sha256:fef21320697370fa1fadc14f72ac3ad8092b021f5371b315be3c9f3bde44c274,3710
- neat-interpolation-0.3.2.6@sha256:05a7516f4ffc86ba1ca4e9c1cddda5a062131ae518e1d423d6f162c214be4cc1,3066
- optparse-applicative-0.15.1.0@sha256:29ff6146aabf54d46c4c8788e8d1eadaea27c94f6d360c690c5f6c93dac4b07e,4810
- megaparsec-8.0.0@sha256:362f85e243ecbcb550e1de6e5c74ba5a50c09edaa1208c99bc5b9fd242227fc6,3808

# Required by morley
- git: https://github.com/serokell/base-noprelude.git
  commit: 1282e0b992b00089d55228a2aa9edc4a3581c319
- hex-text-0.1.0.4
- show-type-0.1.1
- named-0.3.0.1@sha256:2975d50c9c5d88095026ffc1303d2d9be52e5f588a8f8bcb7003a04b79f10a06,2312
- bitvec-1.0.3.0@sha256:f69ed0e463045cb497a7cf1bc808a2e84ea0ce286cf9507983bb6ed8b4bd3993,3977
- co-log-0.4.0.1@sha256:3d4c17f37693c80d1aa2c41669bc3438fac3e89dc5f479e57d79bc3ddc4dfcc5,5087
- colourista-0.1.0.1@sha256:98353ee0e2f5d97d2148513f084c1cd37dfda03e48aa9dd7a017c9d9c0ba710e,3307
- ansi-terminal-0.10.3@sha256:e2fbcef5f980dc234c7ad8e2fa433b0e8109132c9e643bc40ea5608cd5697797,3226
- OddWord-1.0.2.0

# Packages by Adjoint (somewhat unmaintained, hence they require constraints on their deps)
- galois-field-1.0.2
- elliptic-curve-0.3.0
- pairing-1.1.0
# Required by galois-field.
- protolude-0.2.4
- poly-0.4.0.0
# Required by pairing.
- groups-0.4.1.0
# For keyed BLAKE2b and NaCl secret box
- crypto-sodium-0.0.5.0
# Dependencies of crypto-sodium
- NaCl-0.0.5.0
- libsodium-1.0.18.2

nix:
  packages: [zlib]
